##IMPORT LIBRARIES AND DATASETS

In [ ]:
import pandas as pd
import plotly.express as px
from copy import copy
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import plotly.figure_factory as ff
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from tensorflow import keras


In [ ]:
# Read stock prices data
# Read stock prices data
stock_price_df = pd.read_csv('/content/stock.csv')
stock_price_df

Date        AAPL          BA          T        MGM         AMZN  \
0     2012-01-12   60.198570   75.510002  30.120001  12.130000   175.929993   
1     2012-01-13   59.972858   74.599998  30.070000  12.350000   178.419998   
2     2012-01-17   60.671429   75.239998  30.250000  12.250000   181.660004   
3     2012-01-18   61.301430   75.059998  30.330000  12.730000   189.440002   
4     2012-01-19   61.107143   75.559998  30.420000  12.800000   194.449997   
...          ...         ...         ...        ...        ...          ...   
2154  2020-08-05  440.250000  174.279999  29.850000  16.719999  3205.030029   
2155  2020-08-06  455.609985  172.199997  29.840000  18.459999  3225.000000   
2156  2020-08-07  444.450012  170.020004  30.020000  19.030001  3167.459961   
2157  2020-08-10  450.910004  179.410004  30.200001  21.650000  3148.159912   
2158  2020-08-11  437.500000  180.130005  30.200001  21.500000  3080.669922   

             IBM         TSLA         GOOG        sp500  
0     180.550003    28.250000   313.644379  1295.500000  
1     179.160004    22.790001   311.328064  1289.089966  
2     180.000000    26.600000   313.116364  1293.670044  
3     181.070007    26.809999   315.273285  1308.040039  
4     180.520004    26.760000   318.590851  1314.500000  
...          ...          ...          ...          ...  
2154  125.449997  1485.020020  1473.609985  3327.770020  
2155  126.120003  1489.579956  1500.099976  3349.159912  
2156  124.959999  1452.709961  1494.489990  3351.280029  
2157  127.110001  1418.569946  1496.099976  3360.469971  
2158  126.750000  1374.390015  1480.319946  3333.689941  

[2159 rows x 10 columns]

In [ ]:
# Read the stocks volume data

stock_vol_df = pd.read_csv('/content/stock_volume.csv')
stock_vol_df

Date      AAPL        BA         T       MGM     AMZN      IBM  \
0     2012-01-12  53146800   3934500  26511100  17891100  5385800  6881000   
1     2012-01-13  56505400   4641100  22096800  16621800  4753500  5279200   
2     2012-01-17  60724300   3700100  23500200  15480800  5644500  6003400   
3     2012-01-18  69197800   4189500  22015000  18387600  7473500  4600600   
4     2012-01-19  65434600   5397300  25524000  14022900  7096000  8567200   
...          ...       ...       ...       ...       ...      ...      ...   
2154  2020-08-05  30498000  46551000  22991700  18914200  3930000  3675400   
2155  2020-08-06  50607200  32921600  21908700  35867700  3940600  3417100   
2156  2020-08-07  49453300  19301600  30398500  34530300  3929600  3651000   
2157  2020-08-10  53100900  35857700  35514400  71219700  3167300  3968300   
2158  2020-08-11  46871100  60966900  30978300  34357900  3706600  4998500   

         TSLA      GOOG       sp500  
0      729300   3764400  4019890000  
1     5500400   4631800  3692370000  
2     4651600   3832800  4010490000  
3     1260200   5544000  4096160000  
4     1246300  12657800  4465890000  
...       ...       ...         ...  
2154  4978000   1979500  4732220000  
2155  5992300   1995400  4267490000  
2156  8883500   1576600  4104860000  
2157  7522300   1289300  4318570000  
2158  8356000   1452000  5087650000  

[2159 rows x 10 columns]

In [ ]:
# Sort the stock price data based by Date
stock_price_df = stock_price_df.sort_values(by = ['Date'])
stock_price_df

Date        AAPL          BA          T        MGM         AMZN  \
0     2012-01-12   60.198570   75.510002  30.120001  12.130000   175.929993   
1     2012-01-13   59.972858   74.599998  30.070000  12.350000   178.419998   
2     2012-01-17   60.671429   75.239998  30.250000  12.250000   181.660004   
3     2012-01-18   61.301430   75.059998  30.330000  12.730000   189.440002   
4     2012-01-19   61.107143   75.559998  30.420000  12.800000   194.449997   
...          ...         ...         ...        ...        ...          ...   
2154  2020-08-05  440.250000  174.279999  29.850000  16.719999  3205.030029   
2155  2020-08-06  455.609985  172.199997  29.840000  18.459999  3225.000000   
2156  2020-08-07  444.450012  170.020004  30.020000  19.030001  3167.459961   
2157  2020-08-10  450.910004  179.410004  30.200001  21.650000  3148.159912   
2158  2020-08-11  437.500000  180.130005  30.200001  21.500000  3080.669922   

             IBM         TSLA         GOOG        sp500  
0     180.550003    28.250000   313.644379  1295.500000  
1     179.160004    22.790001   311.328064  1289.089966  
2     180.000000    26.600000   313.116364  1293.670044  
3     181.070007    26.809999   315.273285  1308.040039  
4     180.520004    26.760000   318.590851  1314.500000  
...          ...          ...          ...          ...  
2154  125.449997  1485.020020  1473.609985  3327.770020  
2155  126.120003  1489.579956  1500.099976  3349.159912  
2156  124.959999  1452.709961  1494.489990  3351.280029  
2157  127.110001  1418.569946  1496.099976  3360.469971  
2158  126.750000  1374.390015  1480.319946  3333.689941  

[2159 rows x 10 columns]

In [ ]:
# Sort the stock volume data based by Date
stock_vol_df = stock_vol_df.sort_values(by = ['Date'])
stock_vol_df

Date      AAPL        BA         T       MGM     AMZN      IBM  \
0     2012-01-12  53146800   3934500  26511100  17891100  5385800  6881000   
1     2012-01-13  56505400   4641100  22096800  16621800  4753500  5279200   
2     2012-01-17  60724300   3700100  23500200  15480800  5644500  6003400   
3     2012-01-18  69197800   4189500  22015000  18387600  7473500  4600600   
4     2012-01-19  65434600   5397300  25524000  14022900  7096000  8567200   
...          ...       ...       ...       ...       ...      ...      ...   
2154  2020-08-05  30498000  46551000  22991700  18914200  3930000  3675400   
2155  2020-08-06  50607200  32921600  21908700  35867700  3940600  3417100   
2156  2020-08-07  49453300  19301600  30398500  34530300  3929600  3651000   
2157  2020-08-10  53100900  35857700  35514400  71219700  3167300  3968300   
2158  2020-08-11  46871100  60966900  30978300  34357900  3706600  4998500   

         TSLA      GOOG       sp500  
0      729300   3764400  4019890000  
1     5500400   4631800  3692370000  
2     4651600   3832800  4010490000  
3     1260200   5544000  4096160000  
4     1246300  12657800  4465890000  
...       ...       ...         ...  
2154  4978000   1979500  4732220000  
2155  5992300   1995400  4267490000  
2156  8883500   1576600  4104860000  
2157  7522300   1289300  4318570000  
2158  8356000   1452000  5087650000  

[2159 rows x 10 columns]

##EXPLORATORY DATA ANALYSIS AND VISUALISATION

In [ ]:
# Check if Null values exist in stock prices data
stock_price_df.isnull().sum()

Date     0
AAPL     0
BA       0
T        0
MGM      0
AMZN     0
IBM      0
TSLA     0
GOOG     0
sp500    0
dtype: int64

In [ ]:
# Check if Null values exist in stocks volume data
stock_vol_df.isnull().sum()

Date     0
AAPL     0
BA       0
T        0
MGM      0
AMZN     0
IBM      0
TSLA     0
GOOG     0
sp500    0
dtype: int64

In [ ]:
# Get stock prices dataframe info
stock_price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2159 entries, 0 to 2158
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    2159 non-null   object 
 1   AAPL    2159 non-null   float64
 2   BA      2159 non-null   float64
 3   T       2159 non-null   float64
 4   MGM     2159 non-null   float64
 5   AMZN    2159 non-null   float64
 6   IBM     2159 non-null   float64
 7   TSLA    2159 non-null   float64
 8   GOOG    2159 non-null   float64
 9   sp500   2159 non-null   float64
dtypes: float64(9), object(1)
memory usage: 168.8+ KB


In [ ]:
# Get stock volume dataframe info
stock_vol_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2159 entries, 0 to 2158
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    2159 non-null   object
 1   AAPL    2159 non-null   int64 
 2   BA      2159 non-null   int64 
 3   T       2159 non-null   int64 
 4   MGM     2159 non-null   int64 
 5   AMZN    2159 non-null   int64 
 6   IBM     2159 non-null   int64 
 7   TSLA    2159 non-null   int64 
 8   GOOG    2159 non-null   int64 
 9   sp500   2159 non-null   int64 
dtypes: int64(9), object(1)
memory usage: 168.8+ KB


In [ ]:
stock_vol_df.describe()

AAPL            BA             T           MGM          AMZN  \
count  2.159000e+03  2.159000e+03  2.159000e+03  2.159000e+03  2.159000e+03   
mean   5.820332e+07  6.419916e+06  2.832131e+07  9.845582e+06  4.102673e+06   
std    4.568141e+07  9.711873e+06  1.428911e+07  7.295753e+06  2.290722e+06   
min    1.136200e+07  7.889000e+05  6.862400e+06  9.507000e+05  8.813000e+05   
25%    2.769930e+07  3.031850e+06  2.002150e+07  5.796450e+06  2.675700e+06   
50%    4.209420e+07  3.991000e+06  2.485930e+07  7.899800e+06  3.494800e+06   
75%    7.182480e+07  5.325900e+06  3.210565e+07  1.104055e+07  4.768150e+06   
max    3.765300e+08  1.032128e+08  1.950827e+08  9.009820e+07  2.385610e+07   

                IBM          TSLA          GOOG         sp500  
count  2.159000e+03  2.159000e+03  2.159000e+03  2.159000e+03  
mean   4.453090e+06  7.001302e+06  2.498238e+06  3.680732e+09  
std    2.462811e+06  5.781208e+06  1.928407e+06  8.622717e+08  
min    1.193000e+06  3.649000e+05  7.900000e+03  1.248960e+09  
25%    3.111250e+06  3.433450e+06  1.325400e+06  3.211890e+09  
50%    3.825000e+06  5.581100e+06  1.813900e+06  3.526890e+09  
75%    4.937300e+06  8.619550e+06  3.245350e+06  3.933290e+09  
max    3.049020e+07  6.093880e+07  2.497790e+07  9.044690e+09

## PREPARE DATA FOR TRAINING

In [ ]:
# Function to concatenate the date, stock price, and volume in one dataframe
def individual_stock(price_df, vol_df, name):
    return pd.DataFrame({'Date': price_df['Date'], 'Close': price_df[name], 'Volume': vol_df[name]})

In [ ]:
# Define function to return the output (target) data ML Model
# Target stock price today will be tomorrow's price

def trading_window(data):

  n = 1 #1 day window

# Create a column containing the prices for the next 1 days
  data['Target'] = data[['Close']].shift(-n)

  return data

In [ ]:
# Test concatenation function using individual stock
price_volume_df = individual_stock(stock_price_df, stock_vol_df, 'TSLA')
price_volume_df

Date        Close   Volume
0     2012-01-12    28.250000   729300
1     2012-01-13    22.790001  5500400
2     2012-01-17    26.600000  4651600
3     2012-01-18    26.809999  1260200
4     2012-01-19    26.760000  1246300
...          ...          ...      ...
2154  2020-08-05  1485.020020  4978000
2155  2020-08-06  1489.579956  5992300
2156  2020-08-07  1452.709961  8883500
2157  2020-08-10  1418.569946  7522300
2158  2020-08-11  1374.390015  8356000

[2159 rows x 3 columns]

## TRAIN AN LSTM TIME SERIES MODEL

In [60]:
# Use the close and volume data as training data (Input)
training_data = price_volume_df.iloc[:, 1:3].values
training_data

array([[2.82500000e+01, 7.29300000e+05],
       [2.27900010e+01, 5.50040000e+06],
       [2.66000000e+01, 4.65160000e+06],
       ...,
       [1.45270996e+03, 8.88350000e+06],
       [1.41856995e+03, 7.52230000e+06],
       [1.37439001e+03, 8.35600000e+06]])

In [61]:
# Apply feature scaling the data
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_data)

In [62]:
# Create the training and testing data, training data contains present day and previous day values
X = []
y = []
for i in range(1, len(price_volume_df)):
    X.append(training_set_scaled [i-1:i, 0])
    y.append(training_set_scaled [i, 0])

In [63]:
X

[array([0.00336993]),
 array([0.]),
 array([0.00235155]),
 array([0.00248116]),
 array([0.0024503]),
 array([0.00235155]),
 array([0.00245647]),
 array([0.00285765]),
 array([0.00319712]),
 array([0.0037958]),
 array([0.00403651]),
 array([0.00418464]),
 array([0.00387604]),
 array([0.00419081]),
 array([0.00460434]),
 array([0.00515982]),
 array([0.00556101]),
 array([0.00543757]),
 array([0.00564124]),
 array([0.00604243]),
 array([0.00512896]),
 array([0.00536967]),
 array([0.00640658]),
 array([0.00667197]),
 array([0.00702995]),
 array([0.00751754]),
 array([0.00722746]),
 array([0.00705464]),
 array([0.00724597]),
 array([0.00676455]),
 array([0.00668432]),
 array([0.00680159]),
 array([0.00655471]),
 array([0.00717191]),
 array([0.00694354]),
 array([0.0067769]),
 array([0.00636954]),
 array([0.00637572]),
 array([0.00634486]),
 array([0.00737559]),
 array([0.00815943]),
 array([0.00820881]),
 array([0.00771505]),
 array([0.00753606]),
 array([0.00773356]),
 array([0.00752372]),

In [64]:
# Convert the data into array format
X = np.asarray(X)
y = np.asarray(y)

In [65]:
# Split the data
split = int(0.75 * len(X))
X_train = X[:split]
y_train = y[:split]
X_test = X[split:]
y_test = y[split:]

In [66]:
# Reshape the 1D arrays to 3D arrays to feed in the model
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
X_train.shape, X_test.shape

((1618, 1, 1), (540, 1, 1))

In [67]:
# Create the LSTM model
inputs = keras.layers.Input(shape=(X_train.shape[1], X_train.shape[2]))
x = keras.layers.LSTM(150, return_sequences= True)(inputs)
x = keras.layers.Dropout(0.3)(x)

x = keras.layers.LSTM(150, return_sequences=True)(x)
x = keras.layers.Dropout(0.3)(x)

x = keras.layers.LSTM(150)(x)
outputs = keras.layers.Dense(1, activation='linear')(x)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss="mse")
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 1, 1)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 1, 150)              │          91,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 1, 150)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 1, 150)              │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1, 150)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             151 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 452,551 (1.73 MB)

 Trainable params: 452,551 (1.73 MB)

 Non-trainable params: 0 (0.00 B)

In [68]:
# Train the model
history = model.fit(
    X_train, y_train,
    epochs = 20,
    batch_size = 32,
    validation_split = 0.2
)

Epoch 1/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0055 - val_loss: 0.0096
Epoch 2/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0021 - val_loss: 9.3929e-04
Epoch 3/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 1.2932e-04 - val_loss: 2.4978e-05
Epoch 4/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 4.9825e-05 - val_loss: 3.0325e-05
Epoch 5/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 4.3319e-05 - val_loss: 2.6950e-05
Epoch 6/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 3.7872e-05 - val_loss: 2.5173e-05
Epoch 7/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 3.0882e-05 - val_loss: 2.6652e-05
Epoch 8/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 3.4885e-05 - val_loss: 2.8596e-05
Epoch 9/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 3.2562e-05 - val_loss: 2.5364e-05
Epoch 10/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 3.6252e-05 - val_loss: 4.3346e-05
Epoch 11/20
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 3.3104e-05 - val_loss

In [93]:
# K folds cross validation for model

from sklearn.model_selection import KFold

# Define the number of folds
k = 5
kf = KFold(n_splits=k, shuffle=True)

# Initialize a list to store the validation loss for each fold
fold_losses = []

for train_index, val_index in kf.split(X):
  X_train_fold, X_val_fold = X[train_index], X[val_index]
  y_train_fold, y_val_fold = y[train_index], y[val_index]

  # Reshape data for LSTM
  X_train_fold = np.reshape(X_train_fold, (X_train_fold.shape[0], X_train_fold.shape[1], 1))
  X_val_fold = np.reshape(X_val_fold, (X_val_fold.shape[0], X_val_fold.shape[1], 1))

  # Train the model on the training fold
  history = model.fit(
      X_train_fold, y_train_fold,
      epochs=20,
      batch_size=32,
      validation_data=(X_val_fold, y_val_fold)
  )

  # Evaluate the model on the validation fold and store the loss
  val_loss = model.evaluate(X_val_fold, y_val_fold)
  fold_losses.append(val_loss)

# Calculate the average validation loss across all folds
average_val_loss = np.mean(fold_losses)
print("Average Validation Loss:", average_val_loss)


Epoch 1/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 3.0672e-04 - val_loss: 1.6661e-04
Epoch 2/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 3.4966e-04 - val_loss: 1.1636e-04
Epoch 3/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 2.0821e-04 - val_loss: 3.1909e-04
Epoch 4/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 3.8149e-04 - val_loss: 1.4358e-04
Epoch 5/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 1.9321e-04 - val_loss: 1.9889e-04
Epoch 6/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 3.4581e-04 - val_loss: 1.3856e-04
Epoch 7/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 1.8385e-04 - val_loss: 2.0304e-04
Epoch 8/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 2.8004e-04 - val_loss: 1.3311e-04
Epoch 9/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 3.3022e-04 - val_loss: 2.7807e-04
Epoch 10/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 2.7014e-04 - val_loss: 1.3159e-04
Epoch 11/20
54/54 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 2.7072e-0

In [75]:
test_predicted

[0.004764391,
 0.001411098,
 0.003750978,
 0.003879955,
 0.0038492503,
 0.003750978,
 0.0038553867,
 0.004254612,
 0.004592412,
 0.0051881988,
 0.0054277387,
 0.0055751586,
 0.0052680466,
 0.005581299,
 0.0059928373,
 0.0065456573,
 0.0069449283,
 0.0068220776,
 0.007024781,
 0.007424061,
 0.006514945,
 0.006754509,
 0.0077864914,
 0.008050634,
 0.008406933,
 0.008892244,
 0.008603511,
 0.008431505,
 0.0086219385,
 0.0081427805,
 0.008062921,
 0.00817964,
 0.007933925,
 0.008548224,
 0.008320927,
 0.00815507,
 0.0077496376,
 0.0077557713,
 0.007725063,
 0.008750952,
 0.009531149,
 0.0095802955,
 0.009088827,
 0.008910672,
 0.009107256,
 0.008898385,
 0.008886095,
 0.009002823,
 0.008542089,
 0.008345504,
 0.010385092,
 0.01071685,
 0.010661554,
 0.010342088,
 0.010286799,
 0.009881321,
 0.010759857,
 0.008910672,
 0.008591232,
 0.007774206,
 0.007350349,
 0.0077373427,
 0.007952349,
 0.008044494,
 0.0072213504,
 0.0072152065,
 0.007473208,
 0.0077803484,
 0.0077803484,
 0.0070309285,
 

In [82]:
# Get the Closing price data
close = []
for i in training_set_scaled:
  close.append(i[0])


In [83]:
# Create dataframe for the dates, predicted prices and closing price
df_predicted = price_volume_df[1:][['Date']]
df_predicted['Predictions'] = test_predicted
df_predicted['Close'] = close[1:]
df_predicted


Date  Predictions     Close
1     2012-01-13     0.004764  0.000000
2     2012-01-17     0.001411  0.002352
3     2012-01-18     0.003751  0.002481
4     2012-01-19     0.003880  0.002450
5     2012-01-20     0.003849  0.002352
...          ...          ...       ...
2154  2020-08-05     0.875556  0.902494
2155  2020-08-06     0.874463  0.905309
2156  2020-08-07     0.876980  0.882552
2157  2020-08-10     0.856569  0.861481
2158  2020-08-11     0.837558  0.834213

[2158 rows x 3 columns]

In [85]:
# Define interactive plot

def interactive_plot(df, title):
  fig = px.line(df, title = title, x='Date', y=['Close', 'Predictions'])

  fig.show()

# Plot the results
interactive_plot(df_predicted, "Original Vs. Prediction (TSLA)")